version: '3.8'
services:
  health-checker-backend:
    build:
      context: ./healthCheckerBE
    ports:
      - "5000:5000"
    restart: always
    container_name: health-checker-backend
    command: npm run start
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  primary-backend:
    build:
      context: ./primaryBE
    ports:
      - "5001:5001"
    restart: always
    container_name: primary-backend
    command: npm run start
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  frontend:
    build:
      context: ./frontend
    ports:
      - "5002:5002"
    restart: always
    container_name: frontend
    command: npm run start

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

